
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wulan
 */
public class X1_dssquestion extends javax.swing.JFrame {

    /**
     * Creates new form X1_dssquestion
     */
    public X1_dssquestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jQue1 = new javax.swing.JCheckBox();
        jQue2 = new javax.swing.JCheckBox();
        jQue3 = new javax.swing.JCheckBox();
        jQue4 = new javax.swing.JCheckBox();
        jQue5 = new javax.swing.JCheckBox();
        jQue6 = new javax.swing.JCheckBox();
        jQue7 = new javax.swing.JCheckBox();
        jQue8 = new javax.swing.JCheckBox();
        jQue9 = new javax.swing.JCheckBox();
        jQue10 = new javax.swing.JCheckBox();
        jQue11 = new javax.swing.JCheckBox();
        jQue12 = new javax.swing.JCheckBox();
        jQue13 = new javax.swing.JCheckBox();
        jQue14 = new javax.swing.JCheckBox();
        jQue15 = new javax.swing.JCheckBox();
        jQue16 = new javax.swing.JCheckBox();
        jQue17 = new javax.swing.JCheckBox();
        jQue18 = new javax.swing.JCheckBox();
        jQue19 = new javax.swing.JCheckBox();
        jQue20 = new javax.swing.JCheckBox();
        jQue21 = new javax.swing.JCheckBox();
        jQue22 = new javax.swing.JCheckBox();
        jQue23 = new javax.swing.JCheckBox();
        jQue24 = new javax.swing.JCheckBox();
        jQue25 = new javax.swing.JCheckBox();
        jQue26 = new javax.swing.JCheckBox();
        jQue27 = new javax.swing.JCheckBox();
        jQue28 = new javax.swing.JCheckBox();
        jQue29 = new javax.swing.JCheckBox();
        jQue30 = new javax.swing.JCheckBox();
        jQue31 = new javax.swing.JCheckBox();
        jQue32 = new javax.swing.JCheckBox();
        jQue33 = new javax.swing.JCheckBox();
        jQue34 = new javax.swing.JCheckBox();
        jQue35 = new javax.swing.JCheckBox();
        jQue36 = new javax.swing.JCheckBox();
        jQue37 = new javax.swing.JCheckBox();
        jQue38 = new javax.swing.JCheckBox();
        jQue39 = new javax.swing.JCheckBox();
        jQue40 = new javax.swing.JCheckBox();
        jQue41 = new javax.swing.JCheckBox();
        jQue42 = new javax.swing.JCheckBox();
        jQue43 = new javax.swing.JCheckBox();
        jQue44 = new javax.swing.JCheckBox();
        jQue45 = new javax.swing.JCheckBox();
        jQue46 = new javax.swing.JCheckBox();
        jQue47 = new javax.swing.JCheckBox();
        jQue48 = new javax.swing.JCheckBox();
        jNext_X1 = new javax.swing.JButton();
        jHelp_X1 = new javax.swing.JButton();
        jContact_X1 = new javax.swing.JButton();
        jHome_X1 = new javax.swing.JButton();
        jBackground_X1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jQue1.setBackground(new java.awt.Color(255, 255, 255));
        jQue1.setText("Planting and growing corps");
        jQue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue1ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue1);
        jQue1.setBounds(60, 200, 190, 20);

        jQue2.setBackground(new java.awt.Color(255, 255, 255));
        jQue2.setText("Solving math problems");
        jQue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue2ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue2);
        jQue2.setBounds(60, 220, 160, 20);

        jQue3.setBackground(new java.awt.Color(255, 255, 255));
        jQue3.setText("Being in a play");
        jQue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue3ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue3);
        jQue3.setBounds(60, 240, 160, 20);

        jQue4.setBackground(new java.awt.Color(255, 255, 255));
        jQue4.setText("Studying other culture");
        jQue4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue4ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue4);
        jQue4.setBounds(60, 260, 160, 20);

        jQue5.setBackground(new java.awt.Color(255, 255, 255));
        jQue5.setText("Talking to other people at party");
        jQue5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue5ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue5);
        jQue5.setBounds(60, 280, 220, 20);

        jQue6.setBackground(new java.awt.Color(255, 255, 255));
        jQue6.setText("Working with computers");
        jQue6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue6ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue6);
        jQue6.setBounds(60, 300, 160, 23);

        jQue7.setBackground(new java.awt.Color(255, 255, 255));
        jQue7.setText("Working on cars or lownmowers");
        jQue7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue7ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue7);
        jQue7.setBounds(60, 320, 230, 20);

        jQue8.setBackground(new java.awt.Color(255, 255, 255));
        jQue8.setText("Astronomy");
        jQue8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue8ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue8);
        jQue8.setBounds(60, 340, 160, 20);

        jQue9.setBackground(new java.awt.Color(255, 255, 255));
        jQue9.setText("Drawing or painting");
        jQue9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue9ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue9);
        jQue9.setBounds(60, 360, 160, 20);

        jQue10.setBackground(new java.awt.Color(255, 255, 255));
        jQue10.setText("Going to place of worship");
        jQue10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue10ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue10);
        jQue10.setBounds(60, 380, 190, 20);

        jQue11.setBackground(new java.awt.Color(255, 255, 255));
        jQue11.setText("Working on a sales campaign ");
        jQue11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue11ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue11);
        jQue11.setBounds(60, 400, 220, 20);

        jQue12.setBackground(new java.awt.Color(255, 255, 255));
        jQue12.setText("Using a cash register");
        jQue12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue12ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue12);
        jQue12.setBounds(60, 420, 160, 20);

        jQue13.setBackground(new java.awt.Color(255, 255, 255));
        jQue13.setText("Carpentry");
        jQue13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue13ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue13);
        jQue13.setBounds(290, 200, 160, 20);

        jQue14.setBackground(new java.awt.Color(255, 255, 255));
        jQue14.setText("Physics");
        jQue14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue14ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue14);
        jQue14.setBounds(290, 220, 100, 20);

        jQue15.setBackground(new java.awt.Color(255, 255, 255));
        jQue15.setText("Foreign language");
        jQue15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue15ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue15);
        jQue15.setBounds(290, 240, 130, 20);

        jQue16.setBackground(new java.awt.Color(255, 255, 255));
        jQue16.setText("Working with youth");
        jQue16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue16ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue16);
        jQue16.setBounds(290, 260, 160, 20);

        jQue17.setBackground(new java.awt.Color(255, 255, 255));
        jQue17.setText("Buying clothes for a store");
        jQue17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue17ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue17);
        jQue17.setBounds(290, 280, 160, 23);

        jQue18.setBackground(new java.awt.Color(255, 255, 255));
        jQue18.setText("Working from nine to five");
        jQue18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue18ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue18);
        jQue18.setBounds(290, 300, 160, 23);

        jQue19.setBackground(new java.awt.Color(255, 255, 255));
        jQue19.setText("Setting type for a printing job");
        jQue19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue19ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue19);
        jQue19.setBounds(290, 320, 210, 23);

        jQue20.setBackground(new java.awt.Color(255, 255, 255));
        jQue20.setText("Using a chemistry set");
        jQue20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue20ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue20);
        jQue20.setBounds(290, 340, 160, 23);

        jQue21.setBackground(new java.awt.Color(255, 255, 255));
        jQue21.setText("Reading fiction or plays");
        jQue21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue21ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue21);
        jQue21.setBounds(290, 360, 150, 23);

        jQue22.setBackground(new java.awt.Color(255, 255, 255));
        jQue22.setText("Helping people with problems");
        jQue22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue22ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue22);
        jQue22.setBounds(290, 380, 210, 23);

        jQue23.setBackground(new java.awt.Color(255, 255, 255));
        jQue23.setText("Typing reports");
        jQue23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue23ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue23);
        jQue23.setBounds(290, 400, 190, 23);

        jQue24.setBackground(new java.awt.Color(255, 255, 255));
        jQue24.setText("Driving a truck");
        jQue24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue24ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue24);
        jQue24.setBounds(290, 420, 160, 20);

        jQue25.setBackground(new java.awt.Color(255, 255, 255));
        jQue25.setText("Working in a laboratory");
        jQue25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue25ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue25);
        jQue25.setBounds(500, 200, 200, 20);

        jQue26.setBackground(new java.awt.Color(255, 255, 255));
        jQue26.setText("Selling life issurance");
        jQue26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue26ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue26);
        jQue26.setBounds(500, 220, 170, 20);

        jQue27.setBackground(new java.awt.Color(255, 255, 255));
        jQue27.setText("Playing a musical instrument");
        jQue27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue27ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue27);
        jQue27.setBounds(500, 240, 210, 20);

        jQue28.setBackground(new java.awt.Color(255, 255, 255));
        jQue28.setText("Making new friends");
        jQue28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue28ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue28);
        jQue28.setBounds(500, 260, 160, 23);

        jQue29.setBackground(new java.awt.Color(255, 255, 255));
        jQue29.setText("Leading a group");
        jQue29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue29ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue29);
        jQue29.setBounds(500, 280, 160, 23);

        jQue30.setBackground(new java.awt.Color(255, 255, 255));
        jQue30.setText("Following a budget");
        jQue30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue30ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue30);
        jQue30.setBounds(500, 300, 210, 23);

        jQue31.setBackground(new java.awt.Color(255, 255, 255));
        jQue31.setText("Fixing electrical appliances");
        jQue31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue31ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue31);
        jQue31.setBounds(500, 320, 210, 23);

        jQue32.setBackground(new java.awt.Color(255, 255, 255));
        jQue32.setText("Building rocket models");
        jQue32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue32ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue32);
        jQue32.setBounds(500, 340, 170, 23);

        jQue33.setBackground(new java.awt.Color(255, 255, 255));
        jQue33.setText("Writing stories or poetries");
        jQue33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue33ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue33);
        jQue33.setBounds(500, 360, 210, 23);

        jQue34.setBackground(new java.awt.Color(255, 255, 255));
        jQue34.setText("Attending sport events");
        jQue34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue34ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue34);
        jQue34.setBounds(500, 380, 170, 23);

        jQue35.setBackground(new java.awt.Color(255, 255, 255));
        jQue35.setText("Making your opinions heard");
        jQue35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue35ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue35);
        jQue35.setBounds(500, 400, 200, 23);

        jQue36.setBackground(new java.awt.Color(255, 255, 255));
        jQue36.setText("Using business machines");
        jQue36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue36ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue36);
        jQue36.setBounds(500, 420, 210, 20);

        jQue37.setBackground(new java.awt.Color(255, 255, 255));
        jQue37.setText("Building things");
        jQue37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue37ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue37);
        jQue37.setBounds(710, 200, 210, 20);

        jQue38.setBackground(new java.awt.Color(255, 255, 255));
        jQue38.setText("Doing puzzles");
        jQue38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue38ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue38);
        jQue38.setBounds(710, 220, 180, 20);

        jQue39.setBackground(new java.awt.Color(255, 255, 255));
        jQue39.setText("Fashion design");
        jQue39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue39ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue39);
        jQue39.setBounds(710, 240, 160, 20);

        jQue40.setBackground(new java.awt.Color(255, 255, 255));
        jQue40.setText("Belonging to a club");
        jQue40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue40ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue40);
        jQue40.setBounds(710, 260, 160, 23);

        jQue41.setBackground(new java.awt.Color(255, 255, 255));
        jQue41.setText("Giving talks or speeches");
        jQue41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue41ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue41);
        jQue41.setBounds(710, 280, 160, 23);

        jQue42.setBackground(new java.awt.Color(255, 255, 255));
        jQue42.setText("Keeping detailed records");
        jQue42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue42ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue42);
        jQue42.setBounds(710, 300, 180, 23);

        jQue43.setBackground(new java.awt.Color(255, 255, 255));
        jQue43.setText("Wildlife biology");
        jQue43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue43ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue43);
        jQue43.setBounds(710, 320, 160, 23);

        jQue44.setBackground(new java.awt.Color(255, 255, 255));
        jQue44.setText("Using science to get answers");
        jQue44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue44ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue44);
        jQue44.setBounds(710, 340, 200, 23);

        jQue45.setBackground(new java.awt.Color(255, 255, 255));
        jQue45.setText("Going to the concerts or theaters");
        jQue45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue45ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue45);
        jQue45.setBounds(710, 360, 240, 23);

        jQue46.setBackground(new java.awt.Color(255, 255, 255));
        jQue46.setText("Working with the elderly");
        jQue46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue46ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue46);
        jQue46.setBounds(710, 380, 180, 23);

        jQue47.setBackground(new java.awt.Color(255, 255, 255));
        jQue47.setText("Going to the concerts or theaters");
        jQue47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue47ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue47);
        jQue47.setBounds(710, 400, 240, 23);

        jQue48.setBackground(new java.awt.Color(255, 255, 255));
        jQue48.setText("Working with the elderly");
        jQue48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQue48ActionPerformed(evt);
            }
        });
        jPanel1.add(jQue48);
        jQue48.setBounds(710, 420, 180, 23);

        jNext_X1.setBackground(new java.awt.Color(102, 153, 255));
        jNext_X1.setForeground(new java.awt.Color(255, 255, 255));
        jNext_X1.setText("Next");
        jNext_X1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNext_X1ActionPerformed(evt);
            }
        });
        jPanel1.add(jNext_X1);
        jNext_X1.setBounds(450, 480, 80, 29);

        jHelp_X1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jHelp_X1.setForeground(new java.awt.Color(255, 153, 0));
        jHelp_X1.setText("Help");
        jPanel1.add(jHelp_X1);
        jHelp_X1.setBounds(240, 20, 80, 29);

        jContact_X1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jContact_X1.setForeground(new java.awt.Color(255, 153, 0));
        jContact_X1.setText("Contact");
        jContact_X1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContact_X1ActionPerformed(evt);
            }
        });
        jPanel1.add(jContact_X1);
        jContact_X1.setBounds(160, 20, 80, 29);

        jHome_X1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/house-black-building-shape.png"))); // NOI18N
        jPanel1.add(jHome_X1);
        jHome_X1.setBounds(903, 20, 40, 28);

        jBackground_X1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/img_dssquestion5.jpg"))); // NOI18N
        jPanel1.add(jBackground_X1);
        jBackground_X1.setBounds(0, 0, 960, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jQue22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue22ActionPerformed
        if(jQue22.isSelected()){
        HollandInterpreter.answer[0] = 1;
        }
        //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
    }//GEN-LAST:event_jQue22ActionPerformed

    private void jQue17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue17ActionPerformed
        if(jQue17.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue17ActionPerformed

    private void jQue18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue18ActionPerformed
        if(jQue18.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue18ActionPerformed

    private void jQue19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue19ActionPerformed
        if(jQue19.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue19ActionPerformed

    private void jQue20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue20ActionPerformed
        if(jQue20.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue20ActionPerformed

    private void jQue21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue21ActionPerformed
        if(jQue21.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue21ActionPerformed

    private void jQue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue1ActionPerformed
        if(jQue1.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue1ActionPerformed

    private void jQue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue2ActionPerformed
        if(jQue2.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue2ActionPerformed

    private void jQue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue3ActionPerformed
        if(jQue3.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue3ActionPerformed

    private void jQue4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue4ActionPerformed
        if(jQue4.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue4ActionPerformed

    private void jQue5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue5ActionPerformed
        if(jQue5.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue5ActionPerformed

    private void jQue6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue6ActionPerformed
        if(jQue16.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue6ActionPerformed

    private void jQue7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue7ActionPerformed
        if(jQue7.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue7ActionPerformed

    private void jQue8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue8ActionPerformed
        if(jQue8.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue8ActionPerformed

    private void jQue9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue9ActionPerformed
        if(jQue9.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue9ActionPerformed

    private void jQue10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue10ActionPerformed
        if(jQue10.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue10ActionPerformed

    private void jQue11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue11ActionPerformed
        if(jQue11.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue11ActionPerformed

    private void jQue12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue12ActionPerformed
        if(jQue12.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue12ActionPerformed

    private void jQue13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue13ActionPerformed
        if(jQue13.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue13ActionPerformed

    private void jQue14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue14ActionPerformed
        if(jQue14.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue14ActionPerformed

    private void jQue15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue15ActionPerformed
       if(jQue15.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue15ActionPerformed

    private void jQue16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue16ActionPerformed
        if(jQue16.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue16ActionPerformed

    private void jQue23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue23ActionPerformed
        if(jQue23.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue23ActionPerformed

    private void jQue24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue24ActionPerformed
        if(jQue24.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue24ActionPerformed

    private void jQue25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue25ActionPerformed
        if(jQue25.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue25ActionPerformed

    private void jQue26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue26ActionPerformed
        if(jQue26.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue26ActionPerformed

    private void jQue27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue27ActionPerformed
        if(jQue27.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue27ActionPerformed

    private void jQue28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue28ActionPerformed
        if(jQue28.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue28ActionPerformed

    private void jQue29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue29ActionPerformed
        if(jQue29.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue29ActionPerformed

    private void jQue30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue30ActionPerformed
        if(jQue30.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue30ActionPerformed

    private void jQue31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue31ActionPerformed
        if(jQue31.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue31ActionPerformed

    private void jQue32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue32ActionPerformed
        if(jQue32.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue32ActionPerformed

    private void jQue33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue33ActionPerformed
        if(jQue33.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue33ActionPerformed

    private void jQue34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue34ActionPerformed
        if(jQue34.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue34ActionPerformed

    private void jQue35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue35ActionPerformed
        if(jQue35.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue35ActionPerformed

    private void jQue36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue36ActionPerformed
        if(jQue36.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue36ActionPerformed

    private void jQue37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue37ActionPerformed
        if(jQue37.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue37ActionPerformed

    private void jQue38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue38ActionPerformed
        if(jQue38.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue38ActionPerformed

    private void jQue39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue39ActionPerformed
        if(jQue39.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue39ActionPerformed

    private void jQue40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue40ActionPerformed
        if(jQue40.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue40ActionPerformed

    private void jQue41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue41ActionPerformed
        if(jQue41.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue41ActionPerformed

    private void jQue42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue42ActionPerformed
        if(jQue42.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue42ActionPerformed

    private void jQue43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue43ActionPerformed
        if(jQue43.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue43ActionPerformed

    private void jQue44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue44ActionPerformed
        if(jQue44.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue44ActionPerformed

    private void jQue45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue45ActionPerformed
        if(jQue45.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue45ActionPerformed

    private void jQue48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue48ActionPerformed
        if(jQue48.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue48ActionPerformed

    private void jQue47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue47ActionPerformed
        if(jQue47.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue47ActionPerformed

    private void jQue46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQue46ActionPerformed
        if(jQue46.isSelected()){
            HollandInterpreter.answer[0] = 1;
            //JOptionPane.showMessageDialog ( null, HollandInterpreter.answer[0] );
        }
    }//GEN-LAST:event_jQue46ActionPerformed

    private void jNext_X1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNext_X1ActionPerformed
        dispose();
        X2_dssweakness x = new X2_dssweakness();
        x.setVisible(true);
    }//GEN-LAST:event_jNext_X1ActionPerformed

    private void jContact_X1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContact_X1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jContact_X1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(X1_dssquestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(X1_dssquestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(X1_dssquestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(X1_dssquestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new X1_dssquestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackground_X1;
    private javax.swing.JButton jContact_X1;
    private javax.swing.JButton jHelp_X1;
    private javax.swing.JButton jHome_X1;
    private javax.swing.JButton jNext_X1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jQue1;
    private javax.swing.JCheckBox jQue10;
    private javax.swing.JCheckBox jQue11;
    private javax.swing.JCheckBox jQue12;
    private javax.swing.JCheckBox jQue13;
    private javax.swing.JCheckBox jQue14;
    private javax.swing.JCheckBox jQue15;
    private javax.swing.JCheckBox jQue16;
    private javax.swing.JCheckBox jQue17;
    private javax.swing.JCheckBox jQue18;
    private javax.swing.JCheckBox jQue19;
    private javax.swing.JCheckBox jQue2;
    private javax.swing.JCheckBox jQue20;
    private javax.swing.JCheckBox jQue21;
    private javax.swing.JCheckBox jQue22;
    private javax.swing.JCheckBox jQue23;
    private javax.swing.JCheckBox jQue24;
    private javax.swing.JCheckBox jQue25;
    private javax.swing.JCheckBox jQue26;
    private javax.swing.JCheckBox jQue27;
    private javax.swing.JCheckBox jQue28;
    private javax.swing.JCheckBox jQue29;
    private javax.swing.JCheckBox jQue3;
    private javax.swing.JCheckBox jQue30;
    private javax.swing.JCheckBox jQue31;
    private javax.swing.JCheckBox jQue32;
    private javax.swing.JCheckBox jQue33;
    private javax.swing.JCheckBox jQue34;
    private javax.swing.JCheckBox jQue35;
    private javax.swing.JCheckBox jQue36;
    private javax.swing.JCheckBox jQue37;
    private javax.swing.JCheckBox jQue38;
    private javax.swing.JCheckBox jQue39;
    private javax.swing.JCheckBox jQue4;
    private javax.swing.JCheckBox jQue40;
    private javax.swing.JCheckBox jQue41;
    private javax.swing.JCheckBox jQue42;
    private javax.swing.JCheckBox jQue43;
    private javax.swing.JCheckBox jQue44;
    private javax.swing.JCheckBox jQue45;
    private javax.swing.JCheckBox jQue46;
    private javax.swing.JCheckBox jQue47;
    private javax.swing.JCheckBox jQue48;
    private javax.swing.JCheckBox jQue5;
    private javax.swing.JCheckBox jQue6;
    private javax.swing.JCheckBox jQue7;
    private javax.swing.JCheckBox jQue8;
    private javax.swing.JCheckBox jQue9;
    // End of variables declaration//GEN-END:variables
}
