/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wulan
 */
public class X2_dssweakness extends javax.swing.JFrame {

    /**
     * Creates new form X2_dssweakness
     */
    public X2_dssweakness() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBackground_X2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jWeak1 = new javax.swing.JCheckBox();
        jWeak2 = new javax.swing.JCheckBox();
        jWeak4 = new javax.swing.JCheckBox();
        jWeak3 = new javax.swing.JCheckBox();
        jWeak5 = new javax.swing.JCheckBox();
        jPrevious_X2 = new javax.swing.JButton();
        jNext_X2 = new javax.swing.JButton();
        jContact_X2 = new javax.swing.JButton();
        jHome_X1 = new javax.swing.JButton();
        jHelp_X2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jContact_X3 = new javax.swing.JButton();
        jHelp_X3 = new javax.swing.JButton();
        jPrevious_X3 = new javax.swing.JButton();
        jNext_X3 = new javax.swing.JButton();
        jHome_X2 = new javax.swing.JButton();

        jBackground_X2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/img_dssweakness1.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jWeak1.setBackground(new java.awt.Color(255, 255, 255));
        jWeak1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jWeak1.setText("Mathematics");
        jPanel1.add(jWeak1);
        jWeak1.setBounds(420, 200, 130, 30);

        jWeak2.setBackground(new java.awt.Color(255, 255, 255));
        jWeak2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jWeak2.setText("English");
        jPanel1.add(jWeak2);
        jWeak2.setBounds(420, 240, 130, 31);

        jWeak4.setBackground(new java.awt.Color(255, 255, 255));
        jWeak4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jWeak4.setText("Biology");
        jWeak4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWeak4ActionPerformed(evt);
            }
        });
        jPanel1.add(jWeak4);
        jWeak4.setBounds(420, 360, 130, 31);

        jWeak3.setBackground(new java.awt.Color(255, 255, 255));
        jWeak3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jWeak3.setText("Physics");
        jWeak3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWeak3ActionPerformed(evt);
            }
        });
        jPanel1.add(jWeak3);
        jWeak3.setBounds(420, 280, 130, 31);

        jWeak5.setBackground(new java.awt.Color(255, 255, 255));
        jWeak5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jWeak5.setText("Chemistry");
        jWeak5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWeak5ActionPerformed(evt);
            }
        });
        jPanel1.add(jWeak5);
        jWeak5.setBounds(420, 320, 130, 31);

        jPrevious_X2.setBackground(new java.awt.Color(102, 153, 255));
        jPrevious_X2.setForeground(new java.awt.Color(255, 255, 255));
        jPrevious_X2.setText("Previous");
        jPrevious_X2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevious_X2ActionPerformed(evt);
            }
        });
        jPanel1.add(jPrevious_X2);
        jPrevious_X2.setBounds(395, 480, 80, 23);

        jNext_X2.setBackground(new java.awt.Color(102, 153, 255));
        jNext_X2.setForeground(new java.awt.Color(255, 255, 255));
        jNext_X2.setText("Next");
        jNext_X2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNext_X2ActionPerformed(evt);
            }
        });
        jPanel1.add(jNext_X2);
        jNext_X2.setBounds(490, 480, 80, 23);

        jContact_X2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jContact_X2.setForeground(new java.awt.Color(255, 153, 0));
        jContact_X2.setText("Contact");
        jPanel1.add(jContact_X2);
        jContact_X2.setBounds(160, 20, 80, 23);

        jHome_X1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/house-black-building-shape.png"))); // NOI18N
        jHome_X1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHome_X1ActionPerformed(evt);
            }
        });
        jPanel1.add(jHome_X1);
        jHome_X1.setBounds(900, 20, 40, 25);

        jHelp_X2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jHelp_X2.setForeground(new java.awt.Color(255, 153, 0));
        jHelp_X2.setText("Help");
        jPanel1.add(jHelp_X2);
        jHelp_X2.setBounds(240, 20, 80, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/img_dssweakness1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 540);

        jContact_X3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jContact_X3.setForeground(new java.awt.Color(255, 153, 0));
        jContact_X3.setText("Contact");
        jPanel1.add(jContact_X3);
        jContact_X3.setBounds(160, 20, 80, 23);

        jHelp_X3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jHelp_X3.setForeground(new java.awt.Color(255, 153, 0));
        jHelp_X3.setText("Help");
        jPanel1.add(jHelp_X3);
        jHelp_X3.setBounds(240, 20, 80, 23);

        jPrevious_X3.setBackground(new java.awt.Color(102, 153, 255));
        jPrevious_X3.setForeground(new java.awt.Color(255, 255, 255));
        jPrevious_X3.setText("Previous");
        jPrevious_X3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevious_X3ActionPerformed(evt);
            }
        });
        jPanel1.add(jPrevious_X3);
        jPrevious_X3.setBounds(395, 480, 80, 23);

        jNext_X3.setBackground(new java.awt.Color(102, 153, 255));
        jNext_X3.setForeground(new java.awt.Color(255, 255, 255));
        jNext_X3.setText("Next");
        jNext_X3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNext_X3ActionPerformed(evt);
            }
        });
        jPanel1.add(jNext_X3);
        jNext_X3.setBounds(490, 480, 80, 23);

        jHome_X2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/house-black-building-shape.png"))); // NOI18N
        jHome_X2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHome_X2ActionPerformed(evt);
            }
        });
        jPanel1.add(jHome_X2);
        jHome_X2.setBounds(900, 20, 40, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jWeak4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWeak4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWeak4ActionPerformed

    private void jWeak3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWeak3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWeak3ActionPerformed

    private void jWeak5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWeak5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWeak5ActionPerformed

    private void jPrevious_X2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevious_X2ActionPerformed
        dispose();
        X1_dssquestion x = new X1_dssquestion();
        x.setVisible(true);
    }//GEN-LAST:event_jPrevious_X2ActionPerformed

    private void jNext_X2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNext_X2ActionPerformed
    dispose();
        X3_dssgrade x = new X3_dssgrade();
        x.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jNext_X2ActionPerformed

    private void jHome_X1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHome_X1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHome_X1ActionPerformed

    private void jPrevious_X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevious_X3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrevious_X3ActionPerformed

    private void jNext_X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNext_X3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNext_X3ActionPerformed

    private void jHome_X2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHome_X2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHome_X2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(X2_dssweakness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(X2_dssweakness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(X2_dssweakness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(X2_dssweakness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new X2_dssweakness().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackground_X2;
    private javax.swing.JButton jContact_X2;
    private javax.swing.JButton jContact_X3;
    private javax.swing.JButton jHelp_X2;
    private javax.swing.JButton jHelp_X3;
    private javax.swing.JButton jHome_X1;
    private javax.swing.JButton jHome_X2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jNext_X2;
    private javax.swing.JButton jNext_X3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPrevious_X2;
    private javax.swing.JButton jPrevious_X3;
    private javax.swing.JCheckBox jWeak1;
    private javax.swing.JCheckBox jWeak2;
    private javax.swing.JCheckBox jWeak3;
    private javax.swing.JCheckBox jWeak4;
    private javax.swing.JCheckBox jWeak5;
    // End of variables declaration//GEN-END:variables
}
