/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wulan
 */
public class X3_dssgrade extends javax.swing.JFrame {

    /**
     * Creates new form X3_dssgrade
     */
    public X3_dssgrade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jGradeOption1 = new javax.swing.JComboBox<>();
        jGradeOption = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jHome_X3 = new javax.swing.JButton();
        jNext_X3 = new javax.swing.JButton();
        jPrevious_X3 = new javax.swing.JButton();
        jHelp_X3 = new javax.swing.JButton();
        jContact_X3 = new javax.swing.JButton();
        jBackground_X3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Grade Point Average");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(540, 220, 150, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Academic Level");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 220, 150, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Academic Program");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 340, 150, 22);

        jGradeOption1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Science - Mathematics", "Mathematics - Art", "Languages - Art", " " }));
        jPanel1.add(jGradeOption1);
        jGradeOption1.setBounds(240, 370, 140, 20);

        jGradeOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Below grade 10", "Grade 10", "Grade 11", "Grade 12", " " }));
        jPanel1.add(jGradeOption);
        jGradeOption.setBounds(240, 250, 140, 20);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(540, 250, 190, 90);

        jHome_X3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/house-black-building-shape.png"))); // NOI18N
        jHome_X3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHome_X3ActionPerformed(evt);
            }
        });
        jPanel1.add(jHome_X3);
        jHome_X3.setBounds(900, 20, 40, 25);

        jNext_X3.setBackground(new java.awt.Color(102, 153, 255));
        jNext_X3.setForeground(new java.awt.Color(255, 255, 255));
        jNext_X3.setText("Next");
        jNext_X3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNext_X3ActionPerformed(evt);
            }
        });
        jPanel1.add(jNext_X3);
        jNext_X3.setBounds(490, 480, 80, 23);

        jPrevious_X3.setBackground(new java.awt.Color(102, 153, 255));
        jPrevious_X3.setForeground(new java.awt.Color(255, 255, 255));
        jPrevious_X3.setText("Previous");
        jPrevious_X3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevious_X3ActionPerformed(evt);
            }
        });
        jPanel1.add(jPrevious_X3);
        jPrevious_X3.setBounds(395, 480, 80, 23);

        jHelp_X3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jHelp_X3.setForeground(new java.awt.Color(255, 153, 0));
        jHelp_X3.setText("Help");
        jPanel1.add(jHelp_X3);
        jHelp_X3.setBounds(240, 20, 80, 23);

        jContact_X3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jContact_X3.setForeground(new java.awt.Color(255, 153, 0));
        jContact_X3.setText("Contact");
        jContact_X3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContact_X3ActionPerformed(evt);
            }
        });
        jPanel1.add(jContact_X3);
        jContact_X3.setBounds(160, 20, 80, 23);

        jBackground_X3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/img_dssgrade1.jpg"))); // NOI18N
        jPanel1.add(jBackground_X3);
        jBackground_X3.setBounds(0, 0, 960, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPrevious_X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevious_X3ActionPerformed
        dispose();
        X2_dssweakness x = new X2_dssweakness();
        x.setVisible(true);
    }//GEN-LAST:event_jPrevious_X3ActionPerformed

    private void jNext_X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNext_X3ActionPerformed
        dispose();
        X4_dssresult x = new X4_dssresult();
        x.setVisible(true);
    }//GEN-LAST:event_jNext_X3ActionPerformed

    private void jHome_X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHome_X3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHome_X3ActionPerformed

    private void jContact_X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContact_X3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jContact_X3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(X3_dssgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(X3_dssgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(X3_dssgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(X3_dssgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new X3_dssgrade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackground_X3;
    private javax.swing.JButton jContact_X3;
    private javax.swing.JComboBox<String> jGradeOption;
    private javax.swing.JComboBox<String> jGradeOption1;
    private javax.swing.JButton jHelp_X3;
    private javax.swing.JButton jHome_X3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jNext_X3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPrevious_X3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
